name: Check Versions

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at 00:00 UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Check Go Version
      id: check-go-version
      run: |
        GO_LATEST=$(curl -s https://go.dev/VERSION?m=text | head -n 1 | cut -d ' ' -f 1)
        GO_CURRENT=$(grep -oP '(?<=GO_VERSION=)\d+\.\d+\.\d+' Dockerfile)
        if [ "$GO_LATEST" != "$GO_CURRENT" ]; then
          echo "Go version $GO_LATEST is available (current: $GO_CURRENT)"
          echo "::set-output name=result::Go version $GO_LATEST is available (current: $GO_CURRENT)"
        else
          echo "Go version $GO_CURRENT is up-to-date"
          echo "::set-output name=result::Go version $GO_CURRENT is up-to-date"
        fi

    - name: Check Gitleaks Version
      run: |
        GITLEAKS_LATEST=$(curl -s https://api.github.com/repos/zricethezav/gitleaks/releases/latest | jq -r '.tag_name')
        GITLEAKS_CURRENT=$(grep -oP '(?<=GITLEAKS_VERSION=)\d+\.\d+\.\d+' Dockerfile)
        if [ "$GITLEAKS_LATEST" != "$GITLEAKS_CURRENT" ]; then
          echo "Gitleaks version $GITLEAKS_LATEST is available (current: $GITLEAKS_CURRENT)"
        fi

    # Add similar steps for TruffleHog and Talisman

    - name: Send Notification
      if: contains(steps.check-go-version.outputs.result, 'is available')
      run: |
        # Replace with your notification logic, e.g., sending an email or creating an issue
        echo "New versions for Golang is available. Please update the Dockerfile."
